<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JoueurController;
use GuzzleHttp\Psr7\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index Page

Route::get('/', function () {

    if (auth()->check()) {
        // user is logged in prepare user for game
        return redirect()->route('game.ready');
    } else {
        return view('auth.login');
    }
});

// we are ready to play, we just need to confirm username and photo
Route::get('/game_ready', [App\Http\Controllers\HomeController::class, 'ready'])->name('game.ready');

// now we are ready to start game after uploading username and photo
Route::post('/game_start', 'App\Http\Controllers\JoueurController@store')->name('game.start');

// show game board
Route::get('/jeu', 'App\Http\Controllers\LettresController@ChoisirLettresAléatoiresDuReserve')->name('jeu');


// auto generated by laravel/ui for registering and login
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
