<?php

use App\Http\Controllers\JeuAPIController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JoueurController;
use App\Http\Controllers\LettresController;
use App\Http\Controllers\PartieController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index Page

Route::get('/', function () {

    if (auth()->check()) {
        // user is logged in prepare user for game
        return redirect()->route('game.ready');
    } else {
        return view('auth.login');
    }
});


// we are ready to play, we just need to confirm username and photo
Route::get('/game_ready', [HomeController::class, 'ready'])->name('game.ready');

// now we are ready to start game after uploading username and photo
Route::post('/game_start', [JoueurController::class, 'store'])->name('game.start');

// select the game type

Route::get('/game_select', [PartieController::class, 'index'])->name('game.select');

Route::post('/game_select', [PartieController::class, 'store'])->name('game.select');

// Waiting room
Route::get('/game_wait', [PartieController::class, 'wait'])->name('game.wait');

// show game board
Route::get('/jeu', [LettresController::class, 'ChoisirLettresAléatoiresDuReserve'])->name('jeu');

// quitter game
Route::get('/quitter', [PartieController::class, 'quitter'])->name('game.quitter');

// game has ended
Route::get('/ended',[LettresController::class,'game_ended'])->name('game.ended');

// auto generated by laravel/ui for registering and login
Auth::routes();

// login home
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// game timer function
Route::post('game/check_timer',[JeuAPIController::class,'check_timer'])->name('game.checkTimer');

// handle message and chat
Route::post('game/message',[JeuAPIController::class,'message'])->name('game.message');